### ISSUE TITLE
Please update the README?

### ISSUE THREAD

**Issue by davidwang20** [osainz59/Ask2Transformers#1]
This seems like it would be really cool to use but unfortunately the example code in the readme is no longer valid, and I've been struggling for a long time to get this thing to work. It seems "NLITopicClassifier" now requires an additional argument to specify which pretrained model to use, but not all of them work. 

Provide further explanation or documentation?

**Comment by davidwang20** [comment]
For example, here is the stack trace when I try to run NLITopicClassifier using 'gpt2' as the first argument of its contructor in exactly the usage provided in the README:

![image](https://user-images.githubusercontent.com/25164585/111519415-4adc9d80-8714-11eb-82d2-bed54c669261.png)

**Comment by osainz59** [comment]
Hi! You are right, I should give more information about which are the pretrained models expected to be used with the NLITopicClassifier class. I will push a hotfix asap with the indications. 

But for now, the only models that are expected to work are the ones that are already fine-tuned on the MNLI task. For instance you can try the following ones: "roberta-large-mnli", "facebook/bart-large-mnli", "microsoft/deberta-v2-xlarge-mnli", "joeddav/xlm-roberta-large-xnli", etc ... Remember that to use some of them you will need to update your Transformers version.

**Comment by davidwang20** [comment]
I tried with microsoft/deberta-v2-xlarge-mnli and so far its working well. Outside of lack of documentation it is a very cool project 👍.
