### ISSUE TITLE
Tutorial or examples

### ISSUE THREAD

**Issue by ieea** [osainz59/Ask2Transformers#13]
Hi,
Thanks for the framework.
By when tutorial or examples will be available so that we can have a way to utilise the same.
If you have any related to Text Classification & Relation Extraction.. please share.
Regards,
Gaurav

**Comment by osainz59** [comment]
Hi @ieea ,
Thank you for your comment! 
I recommend you to have a look to our [documentation](https://osainz59.github.io/Ask2Transformers/a2t/index.html), there are two very simple examples on how to use the framework to perform both: Text Classification and Relation Extraction. If you are more interested on benchmarking or evaluation scenarios we also provided a general purpose evaluation script ([a2t/evaluation.py](https://github.com/osainz59/Ask2Transformers/blob/master/a2t/evaluation.py)) also available through the documentation [page](https://osainz59.github.io/Ask2Transformers/a2t/evaluation.html). You can find the configuration files we used for evaluation in [a2t/resources/predefined_configs](https://github.com/osainz59/Ask2Transformers/tree/master/resources/predefined_configs) directory.
Lastly, we have also made a Colab Notebook tutorial for using this framework to perform Relation Extraction, unfortunately, the dataset we used ([TACRED](https://nlp.stanford.edu/projects/tacred/)) is not publicly available, so we still do not know how to share this tutorial.

Hope this answer helps you.
Best,
Oscar

**Comment by ieea** [comment]
> Hi @ieea , Thank you for your comment! I recommend you to have a look to our [documentation](https://osainz59.github.io/Ask2Transformers/a2t/index.html), there are two very simple examples on how to use the framework to perform both: Text Classification and Relation Extraction. If you are more interested on benchmarking or evaluation scenarios we also provided a general purpose evaluation script ([a2t/evaluation.py](https://github.com/osainz59/Ask2Transformers/blob/master/a2t/evaluation.py)) also available through the documentation [page](https://osainz59.github.io/Ask2Transformers/a2t/evaluation.html). You can find the configuration files we used for evaluation in [a2t/resources/predefined_configs](https://github.com/osainz59/Ask2Transformers/tree/master/resources/predefined_configs) directory. Lastly, we have also made a Colab Notebook tutorial for using this framework to perform Relation Extraction, unfortunately, the dataset we used ([TACRED](https://nlp.stanford.edu/projects/tacred/)) is not publicly available, so we still do not know how to share this tutorial.
> 
> Hope this answer helps you. Best, Oscar

Thanks Oscar !!
