### ISSUE TITLE
Typo in apostrophes

### ISSUE THREAD

**Issue by mahrahimi1** [osainz59/Ask2Transformers#14]
In the templates in "tacred.relation.config.json", for the relation "per:date_of_birth", there is the following template. 
"{subj}\u00e2\u0080\u0099s birthday is on {obj}."

Shouldn't it be as below?
"{subj}'s birthday is on {obj}."

It looks like the apostrophe character (') is replaced with \u00e2\u0080\u0099. Is that a typo or is it intentional?

There is also the same issue in the following template as well.
"{obj} is the cause of {subj}\u00e2\u0080\u0099s death."

**Comment by osainz59** [comment]
Thank you @mahrahimi1 for pointing it out!

I think that was caused by some encoding issue, I corrected the configuration files.
