### ISSUE TITLE
Few-Shot RE

### ISSUE THREAD

**Issue by mehrdad-naser-73** [osainz59/Ask2Transformers#3]
Hi! 
Do you have any plans for releasing the code for fine-tuning the relation extraction model?

**Comment by osainz59** [comment]
Hi @mehrdad-naser-73 !
I did not use any special code to train the model. I first convert the TACRED data into some kind of NLI data with [tacred2mnli.py](https://github.com/osainz59/Ask2Transformers/blob/master/scripts/tacred2mnli.py) and then use the [run_glue.py](https://github.com/huggingface/transformers/blob/master/examples/pytorch/text-classification/run_glue.py) from the [Transformers](https://github.com/huggingface/transformers) GitHub. You can find the exact copy of the script I used on the [Relation Extraction](https://github.com/osainz59/Ask2Transformers/tree/master/a2t/relation_classification) directory.

I apologize for the lack of documentation this repository has, it is already on my TODOs for this year.

**Comment by osainz59** [comment]
I added this information to the README. Please, if you find insufficient this information, you can re-open the issue :)
