### ISSUE TITLE
Fewshot checkpoints for TACRED

### ISSUE THREAD

**Issue by Lukeming-tsinghua** [osainz59/Ask2Transformers#9]
Hi, I am just wondering if it is possible for you to release fewshot checkpoints for TACRED. Thx!

**Comment by osainz59** [comment]
Hi @Lukeming-tsinghua !

Unfortunately I did not stored all the checkpoints from the past experiments, specially the few-shot ones as there is no real use case for them. I imagine that you want/need these models to replicate the experiments, but as I can not prove that they are trained just with the data split I mention, I decided not to store them. If it is the case I really encourage you to train the models yourself.

However, If you are looking for the full trained models instead, I think I still have the DeBERTa and RoBERTa checkpoints. Let me know if you are interested on those.

**Comment by Lukeming-tsinghua** [comment]
Thanks a lot @osainz59！ I will follow the paper and your codes to train the fewshot models.
